### ISSUE TITLE
Use Array.prototype.map instead of using forEach

### ISSUE THREAD

**Issue by nishant-jain-94** [sro-boeing-wave-2/english-to-braille-js-assignment-problem-saikiran290695#1]
https://github.com/sro-boeing-wave-2/english-to-braille-js-assignment-problem-saikiran290695/blob/fe205209784dcd2a9514ba03dd035f1a652ba23e/index.js#L15-L17

**Comment by nishant-jain-94** [comment]
Array.prototype.map can be referred here from https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map

**Comment by saikiran290695** [comment]
changed foreach to Map
